EMA-150 (#65)
Co-authored-by: Tamás Perencz <tamas.perencz@itgcommerce.com>
Co-authored-by: szsanyi <szsanyi78@gmail.com>
Co-authored-by: Sanyi <sandor.deli-szabo@itgcommerce.com>
Co-authored-by: bognar.tamas <tamas.bognar@itgcommerce.com>
Co-authored-by: itegration-it <39052088+itegration-it@users.noreply.github.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,18 +22,21 @@ jobs:
         shell: bash
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch
+
       - name: Checkout code
         shell: bash
         run: |
           sudo apt-get update
           sudo apt-get install git -y
           git clone --branch ${{ steps.extract_branch.outputs.branch }} https://github.com/emartech/magento2-extension.git
+
       - name: Login to GitLab
         uses: docker/login-action@v3
         with:
           registry: ${{ vars.REGISTRY_URL }}
           username: ${{ secrets.GITLAB_USER }}
           password: ${{ secrets.GITLAB_TOKEN }}
+
       - name: Install system tools
         shell: bash
         run: |
@@ -47,24 +50,52 @@ jobs:
             $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
             sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
-          sudo apt-get install docker-compose-plugin -y
+          sudo apt-get install docker-compose-plugin docker-buildx-plugin -y
+
       - name: Build mage_node image
         shell: bash
         run: |
           cd magento2-extension/dev
-          docker build -f testv2/tools/docker/Dockerfile-mage-node --build-arg NPM_TOKEN=$NPM_TOKEN -t "mage_node" .
+          retries=3
+          count=0
+          until [ $count -ge $retries ]
+          do
+            DOCKER_BUILDKIT=1 docker build -f testv2/tools/docker/Dockerfile-mage-node --build-arg NPM_TOKEN=$NPM_TOKEN -t "mage_node" .  && break
+            count=$((count+1))
+            echo "Retrying build mage_node image ($count/$retries)..."
+            sleep 30
+          done
+          if [ $count -ge $retries ]; then
+            echo "mage_node image building failed after $retries attempts."
+            exit 1
+          fi
         env:
           NPM_TOKEN: ${{ secrets.GITLAB_TOKEN }}
-      - name: Run unittest
+
+      - name: Run unit test
         shell: bash
         run: |
           cd magento2-extension
-          bash dev/testv2/tools/scripts/run-unit.sh
+          retries=3
+          count=0
+          until [ $count -ge $retries ]
+          do
+            bash dev/testv2/tools/scripts/run-unit.sh && break
+            count=$((count+1))
+            echo "Retrying unit tests ($count/$retries)..."
+            sleep 30
+          done
+          if [ $count -ge $retries ]; then
+            echo "unit tests failed after $retries attempts."
+            exit 1
+          fi
         env:
           VERSION: ${{ matrix.magento-versions }}
           NPM_TOKEN: ${{ secrets.GITLAB_TOKEN }}
+
   e2e-tests:
     runs-on: github-actions-runner-emarsys
+#    needs: unit-tests
     permissions:
       contents: "read"
     strategy:
@@ -78,18 +109,21 @@ jobs:
         shell: bash
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch
+
       - name: Checkout code
         shell: bash
         run: |
           sudo apt-get update
           sudo apt-get install git -y
           git clone --branch ${{ steps.extract_branch.outputs.branch }} https://github.com/emartech/magento2-extension.git
+
       - name: Login to GitLab
         uses: docker/login-action@v3
         with:
           registry: ${{ vars.REGISTRY_URL }}
           username: ${{ secrets.GITLAB_USER }}
           password: ${{ secrets.GITLAB_TOKEN }}
+
       - name: Install system tools
         shell: bash
         run: |
@@ -103,19 +137,45 @@ jobs:
             $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
             sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
-          sudo apt-get install docker-compose-plugin -y
+          sudo apt-get install docker-compose-plugin docker-buildx-plugin -y
+
       - name: Build mage_node image
         shell: bash
         run: |
           cd magento2-extension/dev
-          docker build -f testv2/tools/docker/Dockerfile-mage-node --build-arg NPM_TOKEN=$NPM_TOKEN -t "mage_node" .
+          retries=3
+          count=0
+          until [ $count -ge $retries ]
+          do
+            DOCKER_BUILDKIT=1 docker build -f testv2/tools/docker/Dockerfile-mage-node --build-arg NPM_TOKEN=$NPM_TOKEN -t "mage_node" .  && break
+            count=$((count+1))
+            echo "Retrying build mage_node image ($count/$retries)..."
+            sleep 30
+          done
+          if [ $count -ge $retries ]; then
+            echo "mage_node image building failed after $retries attempts."
+            exit 1
+          fi
         env:
           NPM_TOKEN: ${{ secrets.GITLAB_TOKEN }}
-      - name: Run e2stest
+
+      - name: Run e2e test
         shell: bash
         run: |
           cd magento2-extension
-          bash dev/testv2/tools/scripts/run-e2e.sh
+          retries=3
+          count=0
+          until [ $count -ge $retries ]
+          do
+            bash dev/testv2/tools/scripts/run-e2e.sh && break
+            count=$((count+1))
+            echo "Retrying e2e tests ($count/$retries)..."
+            sleep 30
+          done
+          if [ $count -ge $retries ]; then
+            echo "e2e tests failed after $retries attempts."
+            exit 1
+          fi
         env:
           VERSION: ${{ matrix.magento-versions }}
           NPM_TOKEN: ${{ secrets.GITLAB_TOKEN }}
